export const metadata = {
  title: "Privacy Policy | 張園 Zheungyuan",
  description: "Privacy policy for Zheungyuan village-house rental services.",
};

const Section = ({ title, children }) => (
  <section style={{ marginTop: "34px" }}>
    <h2 style={{ fontFamily: 'Georgia, "Times New Roman", serif', fontWeight: 400, fontSize: "28px", margin: "0 0 12px" }}>{title}</h2>
    <div style={{ color: "#58635c", fontSize: "15px", lineHeight: 1.75 }}>{children}</div>
  </section>
);

export default function PrivacyPolicy() {
  return (
    <main style={{ background: "#fbf8f1", minHeight: "100vh" }}>
      <div style={{ background: "#15342c", color: "#f1ecdf", padding: "24px 0" }}>
        <div className="container">
          <a href="/" style={{ display: "inline-flex", alignItems: "baseline", gap: "13px" }}>
            <span style={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: "30px", letterSpacing: ".08em" }}>張園</span>
            <span style={{ fontSize: "10px", textTransform: "uppercase", letterSpacing: ".18em", opacity: 0.8 }}>Zheungyuan</span>
          </a>
        </div>
      </div>

      <div className="container" style={{ maxWidth: "900px", paddingTop: "72px", paddingBottom: "90px" }}>
        <div style={{ color: "#bd9659", fontSize: "11px", fontWeight: 700, letterSpacing: ".16em", textTransform: "uppercase" }}>Privacy</div>
        <h1 style={{ fontFamily: 'Georgia, "Times New Roman", serif', fontSize: "56px", fontWeight: 400, lineHeight: 1.02, margin: "16px 0 12px", color: "#172922" }}>Privacy Policy</h1>
        <p style={{ color: "#7a817c", fontSize: "13px", marginBottom: "34px" }}>Last updated: 13 August 2026</p>

        <p style={{ color: "#58635c", fontSize: "17px", lineHeight: 1.75 }}>
          Zheungyuan / 張園 (“Zheungyuan”, “we”, “us” or “our”) provides village-house rental presentation, enquiry organisation and renter-to-property matching services in Hong Kong. This policy explains how we collect, use, store and disclose personal data when you contact us, enquire about a property, communicate with us through WhatsApp, use our website, or otherwise interact with our rental services.
        </p>

        <Section title="1. Personal data we may collect">
          <p>Depending on how you interact with us, we may collect:</p>
          <ul>
            <li>name, telephone number and WhatsApp/contact identifiers;</li>
            <li>rental enquiry and viewing history;</li>
            <li>messages and information you provide through WhatsApp or other communication channels;</li>
            <li>rental requirements such as area, budget, bedrooms, floor, garden or rooftop preferences, pets, parking, intended move-in timing and household information;</li>
            <li>information about properties you own, manage, list, enquire about or view;</li>
            <li>labels, notes, dates and administrative information used to organise enquiries;</li>
            <li>structured summaries derived from rental-related communications; and</li>
            <li>basic technical or server-log information generated by our website or connected systems.</li>
          </ul>
          <p>Please avoid sending sensitive personal information that is not necessary for a rental enquiry.</p>
        </Section>

        <Section title="2. How we collect personal data">
          <p>We may collect personal data directly from you, through WhatsApp or other communication channels, when you provide property details or arrange a viewing, from records created during our prior communications, and through our website and internal rental systems.</p>
        </Section>

        <Section title="3. How we use personal data">
          <ul>
            <li>respond to rental and property enquiries;</li>
            <li>create and maintain prospective renter and landlord/property records;</li>
            <li>organise historical enquiry and viewing information;</li>
            <li>understand and structure rental requirements;</li>
            <li>identify potentially suitable renter/property matches;</li>
            <li>arrange or coordinate viewings and rental communications;</li>
            <li>prepare and manage property listings;</li>
            <li>maintain security and operational records;</li>
            <li>improve our rental processes and service quality; and</li>
            <li>comply with applicable legal and regulatory requirements.</li>
          </ul>
          <p>We do not make final tenancy decisions using automated systems. AI-assisted analysis is used to organise information and assist matching; landlords and renters remain responsible for their own decisions and agreements.</p>
        </Section>

        <Section title="4. AI-assisted processing">
          <p>We may use AI tools to summarise and structure rental-related communications. For example, an AI tool may identify a prospective renter&apos;s preferred area, budget, floor, garden/rooftop preferences, pet requirements or parking needs.</p>
          <p>When we use our private Zheungyuan Custom GPT, relevant stored enquiry information may be transmitted to OpenAI for processing through ChatGPT. The resulting structured information may then be saved back to our rental database.</p>
          <p>We aim to limit AI processing to information reasonably relevant to the rental service. AI-generated results may be reviewed, corrected or deleted where appropriate.</p>
        </Section>

        <Section title="5. Service providers and disclosure">
          <p>We may use third-party providers, including:</p>
          <ul>
            <li>Railway or similar hosting/database providers;</li>
            <li>OpenAI for AI-assisted analysis through our private Custom GPT;</li>
            <li>WhatsApp / Meta where you communicate with us using WhatsApp; and</li>
            <li>other technical providers reasonably necessary to operate and secure the service.</li>
          </ul>
          <p>We do not sell personal data.</p>
          <p>We may disclose information to a landlord, property owner, renter or other party involved in a potential rental transaction only to the extent appropriate for that transaction, or to advisers, service providers or authorities where reasonably necessary or legally required.</p>
        </Section>

        <Section title="6. Cross-border processing">
          <p>Some service providers may process or store data outside Hong Kong. Where this occurs, we take reasonable steps to use reputable providers and limit the information shared to what is reasonably necessary for the relevant service.</p>
        </Section>

        <Section title="7. Data retention">
          <p>We keep personal data only for as long as reasonably necessary for the purposes for which it was collected, including rental matching, follow-up, operational record-keeping, dispute handling and legal or regulatory requirements.</p>
          <p>Historical rental-enquiry information may be retained where it remains reasonably useful for understanding rental demand or prior dealings. We periodically review stored information and may delete or anonymise information that is no longer reasonably required.</p>
        </Section>

        <Section title="8. Data security">
          <p>We take reasonable technical and organisational steps to protect personal data against unauthorised or accidental access, processing, loss, alteration, disclosure or erasure. Access to internal rental data and connected GPT Actions is restricted using authentication and is not intended to be publicly accessible.</p>
          <p>No method of electronic storage or transmission is completely secure, and we cannot guarantee absolute security.</p>
        </Section>

        <Section title="9. Access, correction and other requests">
          <p>You may contact us to ask whether we hold personal data about you, request access, request correction of inaccurate data, ask us to update your rental requirements or status, or request deletion of information that is no longer reasonably required, subject to any legal or operational reason for retention.</p>
          <p>We may need to verify your identity before responding.</p>
        </Section>

        <Section title="10. Direct marketing">
          <p>We will not use personal data for unrelated direct marketing in a manner that does not comply with applicable Hong Kong privacy requirements. Rental follow-up or property-matching communications will be limited to purposes reasonably connected with the rental enquiry or service unless another permitted basis applies.</p>
        </Section>

        <Section title="11. Children">
          <p>Our service is intended for adults dealing with property rentals. We do not knowingly seek to collect personal data directly from children.</p>
        </Section>

        <Section title="12. Changes to this policy">
          <p>We may update this policy as our service, technology or legal requirements change. The latest version will be published on this website with the updated date.</p>
        </Section>

        <Section title="13. Contact">
          <p>For privacy, access or correction requests, please contact Zheungyuan / 張園 using the contact details published on our website.</p>
          <p><strong>Zheungyuan / 張園</strong><br />Hong Kong</p>
        </Section>

        <div style={{ marginTop: "50px", paddingTop: "24px", borderTop: "1px solid #d9d1c3", fontSize: "12px", color: "#7a817c" }}>
          <a href="/" style={{ color: "#15342c", fontWeight: 700 }}>← Back to Zheungyuan</a>
        </div>
      </div>
    </main>
  );
}
